name: translate_to_sqlite
description: Example to use dbf_reader and transalte the dbase to sqlite3.
version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  sqlite3: ^1.9.1
  dbf_reader:
    path: ../

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

publish_to: none