name: dbf_reader
description: A DBF (dBase) reader written in dart.
version: 0.0.2
repository: https://github.com/3vilb0ny/dbf_reader/tree/main

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  test: ^1.22.1

funding:
  - https://www.buymeacoffee.com/b0nyV